spring:
  application:
    name: dockerbt-api
  data:
    rest:
      detection-strategy: annotated

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://host.docker.internal:2000;databaseName=dockerbt;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Password123
  jpa:
    database: sql_server
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /api/dockerbt/actuator

springdoc:
  api-docs:
    enabled: true
    path: '/api/dockerbt/api-docs'
  swagger-ui:
    path: 'api/dockerbt/swagger'
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.dockerbt.api: INFO